# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672c9a04ff94d2a970e770552260c7cc64ba867845259c220e7f5f239830933fa964932c548ea6c030b36ac568c92c2bebf15192426e73e65694e55704f79120

test:
  secret_key_base: db6520de38bdbe97aba6a03abd336ccffbd21c374e1e16bb4583379ae358eb1fd021cda1adb8b6c5e54468cb99fc6c3ec1693b6782b46ff7ce1b508812a4d971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
